<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Spatial analysis of public health data - 4&nbsp; Spatial models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05_food_bank_accessibility.html" rel="next">
<link href="./03_obesity.html" rel="prev">
<link href="./assets/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./general_images/casa_logo.jpg" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Spatial analysis of public health data</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
    <a href="https://github.com/oxford-mgh-2526/spatial-analysis-of-public-health-practicals" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_spatial_models.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Spatial models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Software installation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_geographic_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Geographic information</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_point_patterns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Point patterns and autocorrelation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_obesity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploring the Spatial Distribution of Points in the Presence of Covariates - Fast-Food Outlets and Schools in London</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_spatial_models.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Spatial models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_food_bank_accessibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Food bank accessibility</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">4.1</span> Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">4.2</span> Data</a>
  <ul class="collapse">
  <li><a href="#loading" id="toc-loading" class="nav-link" data-scroll-target="#loading"><span class="header-section-number">4.2.1</span> Loading</a></li>
  <li><a href="#wrangle" id="toc-wrangle" class="nav-link" data-scroll-target="#wrangle"><span class="header-section-number">4.2.2</span> Wrangle</a></li>
  </ul></li>
  <li><a href="#regression" id="toc-regression" class="nav-link" data-scroll-target="#regression"><span class="header-section-number">4.3</span> Regression</a>
  <ul class="collapse">
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">4.3.1</span> Interpretation</a></li>
  <li><a href="#assumptions-underpinning-linear-regression" id="toc-assumptions-underpinning-linear-regression" class="nav-link" data-scroll-target="#assumptions-underpinning-linear-regression"><span class="header-section-number">4.3.2</span> Assumptions underpinning linear regression</a></li>
  </ul></li>
  <li><a href="#spatial-regression-models" id="toc-spatial-regression-models" class="nav-link" data-scroll-target="#spatial-regression-models"><span class="header-section-number">4.4</span> Spatial regression models</a>
  <ul class="collapse">
  <li><a href="#the-spatial-lag-lagged-dependent-variable-model" id="toc-the-spatial-lag-lagged-dependent-variable-model" class="nav-link" data-scroll-target="#the-spatial-lag-lagged-dependent-variable-model"><span class="header-section-number">4.4.1</span> The spatial lag (lagged dependent variable) model</a></li>
  <li><a href="#the-spatial-error-model" id="toc-the-spatial-error-model" class="nav-link" data-scroll-target="#the-spatial-error-model"><span class="header-section-number">4.4.2</span> The spatial error model</a></li>
  <li><a href="#key-advice" id="toc-key-advice" class="nav-link" data-scroll-target="#key-advice"><span class="header-section-number">4.4.3</span> Key advice</a></li>
  </ul></li>
  <li><a href="#gwr" id="toc-gwr" class="nav-link" data-scroll-target="#gwr"><span class="header-section-number">4.5</span> GWR</a>
  <ul class="collapse">
  <li><a href="#bandwidth" id="toc-bandwidth" class="nav-link" data-scroll-target="#bandwidth"><span class="header-section-number">4.5.1</span> Bandwidth</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model"><span class="header-section-number">4.5.2</span> Model</a></li>
  <li><a href="#map-coefficients" id="toc-map-coefficients" class="nav-link" data-scroll-target="#map-coefficients"><span class="header-section-number">4.5.3</span> Map coefficients</a></li>
  <li><a href="#significance" id="toc-significance" class="nav-link" data-scroll-target="#significance"><span class="header-section-number">4.5.4</span> Significance</a></li>
  </ul></li>
  <li><a href="#including-spatial-features" id="toc-including-spatial-features" class="nav-link" data-scroll-target="#including-spatial-features"><span class="header-section-number">4.6</span> Including spatial features</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/oxford-mgh-2526/spatial-analysis-of-public-health-practicals/edit/main/04_spatial_models.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/oxford-mgh-2526/spatial-analysis-of-public-health-practicals/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Spatial models</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Reading</strong></p>
<ul>
<li><p><a href="https://argoshare.is.ed.ac.uk/healthyr_book/chap07-h1.html">Chapter 7 “Linear Regression”</a> from R for Health Data Science by Ewen Harrison and Riinu Pius (2021). <strong>This chapter is excellent, especially section 7.1</strong>.</p></li>
<li><p><a href="https://maczokni.github.io/crime_mapping_textbook/spatial-regression-models.html">Chapter 9 Spatial regression models</a> from Crime Mapping in R by Juanjo Medina and Reka Solymosi (2019).</p></li>
<li><p><a href="https://onlinelibrary.wiley.com/doi/full/10.1111/gean.12316">GWR a road map</a> by Comber et al.&nbsp;2022.There are related papers that have added to this discussion, such as:</p>
<ul>
<li><a href="https://onlinelibrary.wiley.com/doi/full/10.1111/gean.12345">Taylor Oshan</a></li>
<li><a href="https://onlinelibrary.wiley.com/doi/10.1111/gean.12346">Levi Wolf</a></li>
</ul></li>
</ul>
</div>
</div>
<section id="introduction" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">4.1</span> Introduction</h2>
<p>In this practical you will be introduced to a suite of different models that will allow you to test a variety of research questions and hypotheses through modelling the associations between two or more spatially referenced variables.</p>
<p>In 2023 New Zealand scrapped an anti-smoking law that would mean a generational smoking bad for anyone born after 2008. Instead they limited the number of retailers in 2024 from 6,000 to 600 across the country. With a maximum number per area according to the table set on <a href="https://www.health.govt.nz/publications/maximum-numbers-of-approved-smoked-tobacco-retail-premises-permitted-in-areas-of-new-zealand">Ministry of Health website</a>. Here we will explore the factors that might affect smoking in New Zealand and see if they vary spatially. Obviously this new legislation may (most likely will) influence behaviors from 2024.</p>
<p>This practical will walk you through the common steps that you should go through when building a regression model using spatial data to test a stated research hypothesis; from carrying out some descriptive visualisation and summary statistics, to interpreting the results and using the outputs of the model to inform your next steps.</p>
</section>
<section id="data" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="data"><span class="header-section-number">4.2</span> Data</h2>
<p>This is the same has homework 1….and note, we <strong><em>could use 2023 data</em></strong> as described in the homework 1 task.</p>
<ul>
<li><p>Go to the <a href="https://datafinder.stats.govt.nz/">New Zealand spatial data portal</a> and download the file Territorial Authority 2018 (generalised), <a href="https://www.localcouncils.govt.nz/lgip.nsf/wpg_url/About-Local-Government-Local-Government-In-New-Zealand-Councils-roles-and-functions#TerritorialAuthorities(District%20and%20City%20Councils)">these are city or district councils</a>. Make sure it’s the Territorial Authority 2018 data <strong>not</strong> SA1.</p></li>
<li><p>Go to the <a href="https://www.stats.govt.nz/information-releases/statistical-area-1-dataset-for-2018-census-updated-march-2020">Stats NZ website</a> and download the Statistical area 1 dataset for 2018 for the whole of New Zealand. <strong>Download the csv this time - the one that does not say <em>long</em> </strong></p></li>
</ul>
<p>The figure below explains the geographies of New Zealand, we could replicate this analysis for SA1 or SA2 data.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="https://www.stats.govt.nz/methods/geographic-hierarchy#:~:text=Moving%20up%20the%20hierarchy%2C%20statistical,and%20territorial%20authorities%20and%20represent"><img src="prac4_images/Figure-1_GeoHierarchy_Diagram-with-legend-changes.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%" alt="NZ geographies"></a></p>
</figure>
</div>
<figcaption>NZ geographies</figcaption>
</figure>
</div>
<section id="loading" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="loading"><span class="header-section-number">4.2.1</span> Loading</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ta <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"prac4_data/statsnzterritorial-authority-2018-generalised-SHP/territorial-authority-2018-generalised.shp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `territorial-authority-2018-generalised' from data source 
  `C:\Users\Andy\OneDrive - University College London\Teaching\Guest\Oxford_26\spatial analysis of public health\spatial-analysis-of-public-health-data\prac4_data\statsnzterritorial-authority-2018-generalised-SHP\territorial-authority-2018-generalised.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 68 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 1067061 ymin: 4701317 xmax: 2523320 ymax: 6242140
Projected CRS: NZGD2000 / New Zealand Transverse Mercator 2000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>census <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"prac4_data/SA1_census/Individual_part2_totalNZ-wide_format_updated_16-7-20.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="wrangle" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="wrangle"><span class="header-section-number">4.2.2</span> Wrangle</h3>
<p>The <code>.csv</code> we have loaded contains all the data from the week 1 excel homework in a wide format - that means all the SA1s, SA2s etc are are a new row making a huge data file. Normally i would suggest a cool data sci-ency way to pull out our Territorial Authorities, however i can’t see anything that would work. For example, we could try and detect part of a string like “City” or “District” but they appear in other geographies.</p>
<p>So, until i can think or a better way we are resigned to subsetting by rows!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>census_authorities <span class="ot">&lt;-</span> census <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">32413</span><span class="sc">:</span><span class="dv">32480</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># or</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co">#census_authorities &lt;- census[32413:32480,]%&gt;%</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">#  clean_names()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now in this case the data can be a little hard to read - we have over 350 columns! It might be sensible here to have a look at the excel document we downloaded in the week 1 homework to identify our our variables.</p>
<p>Let’s pull out the following variables from the 2018 data:</p>
<ul>
<li>regular smoker</li>
</ul>
<p>that will be modeled by:</p>
<ul>
<li>median income</li>
<li>home ownership</li>
<li>no qualification, <a href="https://www.careers.govt.nz/articles/ncea-compared-with-school-c-and-bursary/#cID_8307">see the New Zealand gov careers website for what qualification levels mean</a></li>
<li>we’ll also try and include some spatial data (e.g.&nbsp;density of tobacco shops) at the very end…</li>
</ul>
<p>Because we are using spatial units and they may differ in size we should normalise our count data (everything but median income which is continous).</p>
<p>To do so i will use the “total” column for each variable, although you could also use <a href="https://www.stats.govt.nz/information-releases/2018-census-population-and-dwelling-counts#:~:text=The%202018%20Census%20usually%20resident,and%202013%20(0.7%20percent).">population count</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>census_authorities_data <span class="ot">&lt;-</span> census_authorities <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(area_code,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>         area_description,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>         census_2018_smoking_status_01_regular_smoker_curp_15years_and_over,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>         census_2018_smoking_status_total_stated_curp_15years_and_over,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>         census_2018_total_personal_income_median_curp_15years_and_over,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>         census_2018_individual_home_ownership_02_own_or_partly_own_curp_15years_and_over,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>         census_2018_individual_home_ownership_total_stated_curp_15years_and_over,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>         census_2018_highest_qualification_000_no_qualification_curp_15years_and_over,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>         census_2018_highest_qualification_total_stated_curp_15years_and_over</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s check the type of our data…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>datatypelist <span class="ot">&lt;-</span> census_authorities_data <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise_all</span>(class) <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to=</span><span class="st">"All_variables"</span>, </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to=</span><span class="st">"Variable_class"</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>datatypelist</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  All_variables                                                   Variable_class
  &lt;chr&gt;                                                           &lt;chr&gt;         
1 area_code                                                       character     
2 area_description                                                character     
3 census_2018_smoking_status_01_regular_smoker_curp_15years_and_… character     
4 census_2018_smoking_status_total_stated_curp_15years_and_over   character     
5 census_2018_total_personal_income_median_curp_15years_and_over  character     
6 census_2018_individual_home_ownership_02_own_or_partly_own_cur… character     
7 census_2018_individual_home_ownership_total_stated_curp_15year… character     
8 census_2018_highest_qualification_000_no_qualification_curp_15… character     
9 census_2018_highest_qualification_total_stated_curp_15years_an… character     </code></pre>
</div>
</div>
<p>Character! we will need to change that…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>census_authorities_data <span class="ot">&lt;-</span> census_authorities_data <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">c</span>(<span class="st">"census_2018_smoking_status_01_regular_smoker_curp_15years_and_over"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"census_2018_smoking_status_total_stated_curp_15years_and_over"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>         <span class="st">"census_2018_total_personal_income_median_curp_15years_and_over"</span>,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>         <span class="st">"census_2018_individual_home_ownership_02_own_or_partly_own_curp_15years_and_over"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>         <span class="st">"census_2018_individual_home_ownership_total_stated_curp_15years_and_over"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>         <span class="st">"census_2018_highest_qualification_000_no_qualification_curp_15years_and_over"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>         <span class="st">"census_2018_highest_qualification_total_stated_curp_15years_and_over"</span>),</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>        as.numeric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The data is selected and now numeric… let’s normalise…and select what we need</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>census_authorities_data_norm <span class="ot">&lt;-</span> census_authorities_data<span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent_regular_smoker=</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>           (census_2018_smoking_status_01_regular_smoker_curp_15years_and_over<span class="sc">/</span>census_2018_smoking_status_total_stated_curp_15years_and_over)<span class="sc">*</span><span class="dv">100</span>)<span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent_home_owner=</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>           (census_2018_individual_home_ownership_02_own_or_partly_own_curp_15years_and_over<span class="sc">/</span>census_2018_individual_home_ownership_total_stated_curp_15years_and_over)<span class="sc">*</span><span class="dv">100</span>)<span class="sc">%&gt;%</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent_no_qualification=</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>           (census_2018_highest_qualification_000_no_qualification_curp_15years_and_over<span class="sc">/</span> census_2018_highest_qualification_total_stated_curp_15years_and_over)<span class="sc">*</span><span class="dv">100</span>)<span class="sc">%&gt;%</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(area_code,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>         area_description,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>         percent_regular_smoker,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>         percent_home_owner,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>         percent_no_qualification,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>         census_2018_total_personal_income_median_curp_15years_and_over</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>         )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Quick plot…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">qplot</span>(<span class="at">x =</span> percent_no_qualification, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> percent_regular_smoker, </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">data=</span>census_authorities_data_norm)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>q <span class="sc">+</span> <span class="fu">stat_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">size=</span><span class="dv">1</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here, I have plotted the percentage of regular smokers per territorial area against another variable in the dataset that I think might be influential…percentage with no qualification</p>
<p>Remember that my <em>null hypothesis</em> would be that there is no relationship between percentage of regular smokers and percentage with no qualification. If this null hypothesis was true, then I would not expect to see any pattern in the cloud of points plotted above.</p>
<p>As it is, the scatter plot shows that, generally, as the <span class="math inline">\(x\)</span> axis <em>independent variable</em> (percentage with no qualification) goes up, our <span class="math inline">\(y\)</span> axis <em>dependent variable</em> (percent of smokers) goes up. This is not a random cloud of points, but something that indicates there could be a relationship here and so I might be looking to reject my null hypothesis.</p>
<p><strong>Some conventions</strong> - In a regression equation, the dependent variable is always labelled <span class="math inline">\(y\)</span> and shown on the <span class="math inline">\(y\)</span> axis of a graph, the predictor or independent variable(s) is(are) always shown on the <span class="math inline">\(x\)</span> axis.</p>
<p>I have added a blue line of best-fit - this is the line that can be drawn by minimising the sum of the squared differences between the line and the residuals. The residuals are all of the dots not falling exactly on the blue line. An algorithm known as ‘ordinary least squares’ (OLS) is used to draw this line and it simply tries a selection of different lines until the sum of the squared differences between all of the residuals and the blue line is minimised, leaving the final solution.</p>
<p>As a general rule, the better the blue line is at summarising the relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span>, the better the model.</p>
<p>The equation for the blue line in the graph above can be written:</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1x_i + \epsilon_i\]</span></p>
<p>where:</p>
<p><span class="math inline">\(\beta_0\)</span> is the intercept (the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span> - somewhere around 4 on the graph above);</p>
<p><span class="math inline">\(\beta_1\)</span> is sometimes referred to as the ‘slope’ parameter and is simply the change in the value of <span class="math inline">\(y\)</span> for a 1 unit change in the value of <span class="math inline">\(x\)</span> (the slope of the blue line) - reading the graph above, the change in the value of <span class="math inline">\(y\)</span> reading between 20 and 15 on the <span class="math inline">\(x\)</span> axis looks to be around a change from 15 to 17.5 on the <span class="math inline">\(y\)</span> - about 0.5 per 1 unit value of <span class="math inline">\(x\)</span>.</p>
<p><span class="math inline">\(\epsilon_i\)</span> is a random error term (positive or negative) that should sum to 0 - essentially, if you add all of the vertical differences between the blue line and all of the residuals, it should sum to 0.</p>
<p>Any value of <span class="math inline">\(y\)</span> along the blue line can be modeled using the corresponding value of <span class="math inline">\(x\)</span> and these parameter values. Examining the graph above we would expect the percent smoking in an area where 26% of the population to not have any qualifications, to equal around 17%, but we can confirm this by plugging the <span class="math inline">\(\beta\)</span> parameter values and the value of <span class="math inline">\(x\)</span> into equation (1):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="dv">4</span> <span class="sc">+</span> (<span class="fl">0.5</span><span class="sc">*</span><span class="dv">26</span>) <span class="sc">+</span> <span class="dv">0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17</code></pre>
</div>
</div>
</section>
</section>
<section id="regression" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="regression"><span class="header-section-number">4.3</span> Regression</h2>
<p>In the graph above, I used a method called ‘lm’ in the <code>stat_smooth()</code> function in <code>ggplot2</code> to draw the regression line. ‘lm’ stands for ‘linear model’ and is a standard function in R for running linear regression models. Use the help system to find out more about <code>lm</code> - <code>?lm</code></p>
<p>Below is the code that could be used to draw the blue line in our scatter plot. Note, the tilde <code>~</code> symbol means “is modeled by”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#now model</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> census_authorities_data_norm <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(percent_regular_smoker <span class="sc">~</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>       percent_no_qualification,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">data=</span>.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s have a closer look at our model…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#show the summary of those outputs</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = percent_regular_smoker ~ percent_no_qualification, 
    data = .)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.7961 -2.3344 -0.5826  1.1691 16.4704 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               1.20258    1.98667   0.605    0.547    
percent_no_qualification  0.64634    0.08289   7.798  6.1e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.588 on 66 degrees of freedom
Multiple R-squared:  0.4795,    Adjusted R-squared:  0.4716 
F-statistic:  60.8 on 1 and 66 DF,  p-value: 6.097e-11</code></pre>
</div>
</div>
<section id="interpretation" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">4.3.1</span> Interpretation</h3>
<p>In running a regression model, we are effectively trying to test (disprove) our null hypothesis. If our null hypothesis was true, then we would expect our coefficients to = 0.</p>
<p>In the output summary of the model above, there are a number of features you should pay attention to:</p>
<p><strong>Coefficient Estimates</strong> - these are the <span class="math inline">\(\beta_0\)</span> (intercept) and <span class="math inline">\(\beta_1\)</span> (slope) parameter estimates from Equation 1. You will notice that at <span class="math inline">\(\beta_0 = 1.2\)</span> and <span class="math inline">\(\beta_1 = 0.64\)</span> they are pretty close (not awful!) to the estimates of 4 and 0.5 that we read from the graph earlier, but more precise.</p>
<p><strong>Coefficient Standard Errors</strong> - these represent the average amount the coefficient varies from the average value of the dependent variable (its standard deviation). So, for a 1% increase in percent with no qualifications, while the model says we might expect percent of smokers to rise by 0.6%, this might vary, on average, by about 0.08%. As a rule of thumb, we are looking for a lower value in the standard error relative to the size of the coefficient.</p>
<p><strong>Note that is the coefficient represents a one unit change, here it is %, as the variable is % unauthorized absence in school</strong> So one unit is a 1% change…</p>
<p><strong>Coefficient t-value</strong> - this is the value of the coefficient divided by the standard error and so can be thought of as a kind of standardised coefficient value. The larger (either positive or negative) the value the greater the relative effect that particular independent variable is having on the dependent variable (this is perhaps more useful when we have several independent variables in the model) .</p>
<p><strong>Coefficient p-value - Pr(&gt;|t|)</strong> - the p-value is a measure of significance. There is lots of debate about p-values which I won’t go into here, but essentially it refers to the probability of getting a coefficient as large as the one observed in a set of random data. p-values can be thought of as percentages, so if we have a p-value of 0.5, then there is a 5% chance that our coefficient could have occurred in some random data, or put another way, a 95% chance that out coefficient could have only occurred in our data.</p>
<p>As a rule of thumb, the smaller the p-value, the more significant that variable is in the story and the smaller the chance that the relationship being observed is just random. Generally, statisticians use 5% or 0.05 as the acceptable cut-off for statistical significance - anything greater than that we should be a little sceptical about.</p>
<p>In <code>r</code> the codes <code>***, **, **, .</code> are used to indicate significance. We generally want at least a single <code>*</code> next to our coefficient for it to be worth considering.</p>
<p><strong>R-Squared</strong> - This can be thought of as an indication of how good your model is - a measure of ‘goodness-of-fit’ (of which there are a number of others). <span class="math inline">\(r^2\)</span> is quite an intuitive measure of fit as it ranges between 0 and 1 and can be thought of as the % of variation in the dependent variable (in our case percentage of smokers) explained by variation in the independent variable(s). In our example, an <span class="math inline">\(r^2\)</span> value of 0.47 indicates that around 47% of the variation in percentage of smokers can be explained by variation in percentage with no qualifications. In other words, this is quite a good model. The <span class="math inline">\(r^2\)</span> value will increase as more independent explanatory variables are added into the model, so where this might be an issue, the adjusted r-squared value can be used to account for this affect.</p>
</section>
<section id="assumptions-underpinning-linear-regression" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="assumptions-underpinning-linear-regression"><span class="header-section-number">4.3.2</span> Assumptions underpinning linear regression</h3>
<section id="assumption-1---there-is-a-linear-relationship-between-the-dependent-and-independent-variables" class="level4" data-number="4.3.2.1">
<h4 data-number="4.3.2.1" class="anchored" data-anchor-id="assumption-1---there-is-a-linear-relationship-between-the-dependent-and-independent-variables"><span class="header-section-number">4.3.2.1</span> Assumption 1 - there is a linear relationship between the dependent and independent variables</h4>
<p>The best way to test for this assumption is to plot a scatter plot similar to the one created earlier. It may not always be practical to create a series of scatter plots, so one quick way to check that a linear relationship is probable is to look at the frequency distributions of the variables. If they are normally distributed, then there is a good chance that if the two variables are in some way correlated, this will be a linear relationship.</p>
<p>For example, look at the frequency distributions of our two variables earlier:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let's check the distribution of these variables first</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(census_authorities_data_norm,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>percent_regular_smoker)) <span class="sc">+</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">colour=</span><span class="st">"red"</span>, </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">size=</span><span class="dv">1</span>, </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">adjust=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here, adding <code>after_stat(density)</code> means that the histogram is a density plot, this plots the chance that any value in the data is equal to that value.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(census_authorities_data_norm,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x=</span>percent_home_owner)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">colour=</span><span class="st">"red"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">size=</span><span class="dv">1</span>, </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">adjust=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It is not a requirement of regression to have normally distributed variables, however if they aren’t the residuals may well be normally distributed, but could vary (meaning we have hetroscedasticity) which we discuss later on.</p>
<p>One way that we might be able to achieve a linear relationship between our two variables is to transform the non-normally distributed variable so that it is more normally distributed. For more information on this see <a href="https://andrewmaclachlan.github.io/CASA0005repo/explaining-spatial-patterns.html#transforming-variables">transforming variables</a>.</p>
<p><strong>However</strong> you will be changing the relationship of your data - it won’t be linear anymore! This could improve your model but is at the expense of interpretation. Aside from log transformation which has the rules in the link above.</p>
<p>Typically if you do a power transformation you can keep the direction of the relationship (positive or negative) and the t-value will give an idea of the importance of the variable in the model - that’s about it!</p>
</section>
<section id="assumption-2---the-residuals-in-your-model-should-be-normally-distributed" class="level4" data-number="4.3.2.2">
<h4 data-number="4.3.2.2" class="anchored" data-anchor-id="assumption-2---the-residuals-in-your-model-should-be-normally-distributed"><span class="header-section-number">4.3.2.2</span> Assumption 2 - the residuals in your model should be normally distributed</h4>
<p>This assumption is easy to check. When we ran our <code>model1</code> earlier, one of the outputs stored in our <code>model1</code> object is the residual value for each case (authority) in your dataset. We can access these values using <code>augment()</code> from <code>broom</code> which will add model output to the original data…</p>
<p>We can plot these as a histogram and see if there is a normal distribution:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co">#save the residuals into your dataframe</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>model_data <span class="ot">&lt;-</span> model1 <span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(., census_authorities_data_norm)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co">#plot residuals</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>model_data<span class="sc">%&gt;%</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">select</span>(.resid)<span class="sc">%&gt;%</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>()<span class="sc">%&gt;%</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">qplot</span>()<span class="sc">+</span> </span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Examining the histogram above, i am happy this is rather normal although there is evidently an outlier in our data somewhere.</p>
</section>
<section id="assumption-3---no-multicolinearity-in-the-independent-variables" class="level4" data-number="4.3.2.3">
<h4 data-number="4.3.2.3" class="anchored" data-anchor-id="assumption-3---no-multicolinearity-in-the-independent-variables"><span class="header-section-number">4.3.2.3</span> Assumption 3 - no multicolinearity in the independent variables</h4>
<p>Now, the regression model we have be experimenting with so far is a simple bivariate (two variable) model. One of the nice things about regression modelling is while we can only easily visualise linear relationships in a two (or maximum 3) dimension scatter plot, mathematically, we can have as many dimensions / variables as we like.</p>
<p>As such, we could extend model 1 into a multiple regression model by adding some more explanatory variables that we think could affect the percentage of people smoking…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(percent_regular_smoker <span class="sc">~</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>               percent_no_qualification <span class="sc">+</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>               percent_home_owner <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>               census_2018_total_personal_income_median_curp_15years_and_over,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> census_authorities_data_norm)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = percent_regular_smoker ~ percent_no_qualification + 
    percent_home_owner + census_2018_total_personal_income_median_curp_15years_and_over, 
    data = census_authorities_data_norm)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.9633 -1.6181 -0.4151  1.3204 12.1627 

Coefficients:
                                                                 Estimate
(Intercept)                                                     1.762e+01
percent_no_qualification                                        7.757e-01
percent_home_owner                                             -3.992e-01
census_2018_total_personal_income_median_curp_15years_and_over -3.922e-05
                                                               Std. Error
(Intercept)                                                     5.089e+00
percent_no_qualification                                        9.198e-02
percent_home_owner                                              7.015e-02
census_2018_total_personal_income_median_curp_15years_and_over  9.961e-05
                                                               t value Pr(&gt;|t|)
(Intercept)                                                      3.463 0.000959
percent_no_qualification                                         8.433 5.57e-12
percent_home_owner                                              -5.690 3.40e-07
census_2018_total_personal_income_median_curp_15years_and_over  -0.394 0.695119
                                                                  
(Intercept)                                                    ***
percent_no_qualification                                       ***
percent_home_owner                                             ***
census_2018_total_personal_income_median_curp_15years_and_over    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.96 on 64 degrees of freedom
Multiple R-squared:  0.6564,    Adjusted R-squared:  0.6403 
F-statistic: 40.75 on 3 and 64 DF,  p-value: 7.514e-15</code></pre>
</div>
</div>
<p>Examining the output above, it is clear that including these variables into our model improves the fit from an <span class="math inline">\(r^2\)</span> of around 47% to an <span class="math inline">\(r^2\)</span> of 65%. However, income is not significant so we should consider removing it..</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(percent_regular_smoker <span class="sc">~</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>               percent_no_qualification <span class="sc">+</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>               percent_home_owner ,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> census_authorities_data_norm)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = percent_regular_smoker ~ percent_no_qualification + 
    percent_home_owner, data = census_authorities_data_norm)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.6020 -1.6175 -0.3927  1.2883 11.7795 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              16.02096    3.04321   5.264 1.70e-06 ***
percent_no_qualification  0.79755    0.07283  10.950  &lt; 2e-16 ***
percent_home_owner       -0.40092    0.06955  -5.764 2.45e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.941 on 65 degrees of freedom
Multiple R-squared:  0.6556,    Adjusted R-squared:  0.645 
F-statistic: 61.86 on 2 and 65 DF,  p-value: 9.037e-16</code></pre>
</div>
</div>
<p>Here we see the <span class="math inline">\(r^2\)</span> is almost the same. But do our two explanatory variables satisfy the no-multicoliniarity assumption? If not and the variables are highly correlated, then we are effectively double counting the influence of these variables and overstating their explanatory power</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="prac4_images/multicollinearity_explain.png" class="img-fluid figure-img" style="width:6.25in"></p>
<figcaption>Word anatomy of multicollinearity. Source: <a href="https://medium.com/geekculture/what-the-heck-is-multicollinearity-c5582ddbb2f7">What the Heck is Multicollinearity?, Andrew Ozbun</a></figcaption>
</figure>
</div>
</div>
</div>
<p>To check this, we can compute the product moment correlation coefficient between the variables, using the <code>corrr()</code> package, that’s part of <code>tidymodels</code>. In an ideal world, we would be looking for something less than a 0.8 correlation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrr)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> census_authorities_data_norm <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(percent_no_qualification, </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>               percent_home_owner)<span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">correlate</span>()</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co">#visualise the correlation matrix</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rplot</span>(correlation)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `aes_string()` was deprecated in ggplot2 3.0.0.
ℹ Please use tidy evaluation idioms with `aes()`.
ℹ See also `vignette("ggplot2-in-packages")` for more information.
ℹ The deprecated feature was likely used in the corrr package.
  Please report the issue at &lt;https://github.com/tidymodels/corrr/issues&gt;.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>correlation</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  term                     percent_no_qualification percent_home_owner
  &lt;chr&gt;                                       &lt;dbl&gt;              &lt;dbl&gt;
1 percent_no_qualification                   NA                  0.360
2 percent_home_owner                          0.360             NA    </code></pre>
</div>
</div>
<p>Another way that we can check for Multicolinearity is to examine the VIF for the model. If we have VIF values for any variable exceeding 10, then we may need to worry and perhaps remove that variable from the analysis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>percent_no_qualification       percent_home_owner 
                1.149067                 1.149067 </code></pre>
</div>
</div>
</section>
<section id="assumption-4---homoscedasticity" class="level4" data-number="4.3.2.4">
<h4 data-number="4.3.2.4" class="anchored" data-anchor-id="assumption-4---homoscedasticity"><span class="header-section-number">4.3.2.4</span> Assumption 4 - homoscedasticity</h4>
<p>Homoscedasticity means that the errors/residuals in the model exhibit constant / homogeneous variance, if they don’t, then we would say that there is hetroscedasticity present. Why does this matter? Andy Field does a much better job of explaining this in <a href="https://www.discoveringstatistics.com/tag/homoscedasticity/">discovering statistics</a> — but essentially, if your errors do not have constant variance, then your parameter estimates could be wrong, as could the estimates of their significance.</p>
<p>The best way to check for homo/hetroscedasticity is to plot the residuals in the model against the predicted values. We are looking for a cloud of points with no apparent patterning to them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#print some model diagnositcs. </span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))    <span class="co">#plot to 2 by 2 array</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>In the series of plots above, the first plot (residuals vs fitted), we would hope to find a random cloud of points with a straight horizontal red line. Looking at the plot, the curved red line would suggest some hetroscedasticity, but the cloud looks quite random. Similarly we are looking for a random cloud of points with no apparent patterning or shape in the third plot of standardised residuals vs fitted values. Here, the cloud of points also looks fairly random, with perhaps some shaping indicated by the red line.</p>
<p><a href="https://jhudatascience.org/tidyversecourse/model.html#model-diagnostics">Section 5.7.6 in Tidyverse Skills for Data Science explains each of these plots in more detail</a></p>
<p>In the plots here we are looking for:</p>
<ul>
<li><p>Residuals vs Fitted: a flat and horizontal line. This is looking at the linear relationship assumption between our variables</p></li>
<li><p>Normal Q-Q: all points falling on the line. This checks if the residuals (observed minus predicted) are normally distributed</p></li>
<li><p>Scale vs Location: flat and horizontal line, with randomly spaced points. This is <strong>the homoscedasticity</strong> (errors/residuals in the model exhibit constant / homogeneous variance). Are the residuals (also called errors) spread equally along all of the data.</p></li>
<li><p>Residuals vs Leverage - Identifies outliers (or influential observations), the three largest outliers are identified with values in the plot.</p></li>
</ul>
<p>The University of Viginia Library provides <a href="https://data.library.virginia.edu/diagnostic-plots/#:~:text=Scale%2DLocation,equally%20(randomly)%20spread%20points.">examples of good and bad models in relation to these plots</a>.</p>
<p>There is an easier way to produce this plot using <code>check_model()</code> from the <code>performance</code> package, that even includes what you are looking for…note that the Posterior predictive check is the comparison between the fitted model and the observed data.</p>
<p>The default argument is <code>check=all</code> but we can specify what to check for…see the <a href="https://rdrr.io/cran/performance/man/check_model.html">arguments section in the documentation</a>…e.g.&nbsp;<code>check = c("vif", "qq")</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(model2, <span class="at">check=</span><span class="st">"all"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="assumption-5---independence-of-errors" class="level4" data-number="4.3.2.5">
<h4 data-number="4.3.2.5" class="anchored" data-anchor-id="assumption-5---independence-of-errors"><span class="header-section-number">4.3.2.5</span> Assumption 5 - independence of errors</h4>
<p>This assumption simply states that the residual values (errors) in your model must not be correlated in any way. If they are, then they exhibit <em>autocorrelation</em> which suggests that something might be going on in the background that we have not sufficiently accounted for in our model.</p>
<section id="standard-autocorrelation" class="level5" data-number="4.3.2.5.1">
<h5 data-number="4.3.2.5.1" class="anchored" data-anchor-id="standard-autocorrelation"><span class="header-section-number">4.3.2.5.1</span> Standard autocorrelation</h5>
<p>If you are running a regression model on data that do not have explicit space or time dimensions, then the standard test for autocorrelation would be the Durbin-Watson test.</p>
<p>This tests whether residuals are correlated and produces a summary statistic that ranges between 0 and 4, with 2 signifying no autocorrelation. A value greater than 2 suggesting negative autocorrelation and and value of less than 2 indicating positive autocorrelation.</p>
<p>In his <a href="https://www.discoveringstatistics.com/books/discovering-statistics-using-r/">excellent text book</a>, Andy Field suggests that you should be concerned with Durbin-Watson test statistics &lt;1 or &gt;3. So let’s see:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#run durbin-watson test</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dw <span class="ot">&lt;-</span> <span class="fu">durbinWatsonTest</span>(model2)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(dw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  statistic p.value autocorrelation method             alternative
      &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;      
1      1.41  0.0140           0.227 Durbin-Watson Test two.sided  </code></pre>
</div>
</div>
<p>As you can see, the DW statistics for our model is 1.41, so some indication of autocorrelation, but perhaps nothing to worry about.</p>
</section>
<section id="spatial-autocorrelation" class="level5" data-number="4.3.2.5.2">
<h5 data-number="4.3.2.5.2" class="anchored" data-anchor-id="spatial-autocorrelation"><span class="header-section-number">4.3.2.5.2</span> Spatial autocorrelation</h5>
<p><strong>HOWEVER</strong></p>
<p>We are using spatially referenced data and as such we should check for <em>spatial</em>-autocorrelation.</p>
<p>The first test we should carry out is to map the residuals to see if there are any apparent obvious patterns:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#and for future use, write the residuals out</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>model2_residuals <span class="ot">&lt;-</span> model2 <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(., census_authorities_data_norm)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>ta_model_data<span class="ot">&lt;-</span> ta<span class="sc">%&gt;%</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>(.)<span class="sc">%&gt;%</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(., model2_residuals,</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">by=</span><span class="fu">c</span>(<span class="st">"ta2018_v1"</span><span class="ot">=</span><span class="st">"area_code"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co">#now plot the residuals</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>ℹ tmap modes "plot" - "view"
ℹ toggle with `tmap::ttm()`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(ta_model_data) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">".resid"</span>,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"RdYlBu"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
── tmap v3 code detected ───────────────────────────────────────────────────────
[v3-&gt;v4] `tm_tm_polygons()`: migrate the argument(s) related to the scale of
the visual variable `fill` namely 'palette' (rename to 'values') to fill.scale
= tm_scale(&lt;HERE&gt;).[cols4all] color palettes: use palettes from the R package cols4all. Run
`cols4all::c4a_gui()` to explore them. The old palette name "RdYlBu" is named
"brewer.rd_yl_bu"Multiple palettes called "rd_yl_bu" found: "brewer.rd_yl_bu", "matplotlib.rd_yl_bu". The first one, "brewer.rd_yl_bu", is returned.
[scale] tm_polygons:() the data variable assigned to 'fill' contains positive and negative values, so midpoint is set to 0. Set 'midpoint = NA' in 'fill.scale = tm_scale_intervals(&lt;HERE&gt;)' to use all visual values (e.g. colors)</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now, we can immediately see some issues with this…</p>
<ol type="1">
<li>I have left the data “outside territorial authority” in the data and it has a large negative residual</li>
<li>Chatham Islands has been included and is also a large positive residual.</li>
</ol>
<p>For the purposes of this practical let’s remove them and re-run the model…</p>
<p><strong>Note</strong> i have added in median income and it is now significant!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>census_authorities_data_norm_filter <span class="ot">&lt;-</span> census_authorities_data_norm <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># != means not equal to</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(area_code <span class="sc">!=</span> <span class="st">"999"</span> <span class="sc">&amp;</span> area_code <span class="sc">!=</span> <span class="st">"067"</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(percent_regular_smoker <span class="sc">~</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>               percent_no_qualification <span class="sc">+</span> </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>               percent_home_owner <span class="sc">+</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>               census_2018_total_personal_income_median_curp_15years_and_over,</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> census_authorities_data_norm_filter)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = percent_regular_smoker ~ percent_no_qualification + 
    percent_home_owner + census_2018_total_personal_income_median_curp_15years_and_over, 
    data = census_authorities_data_norm_filter)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.6984 -1.5153 -0.4655  1.2802  5.3085 

Coefficients:
                                                                 Estimate
(Intercept)                                                     2.796e+01
percent_no_qualification                                        5.152e-01
percent_home_owner                                             -3.051e-01
census_2018_total_personal_income_median_curp_15years_and_over -3.295e-04
                                                               Std. Error
(Intercept)                                                     3.939e+00
percent_no_qualification                                        7.357e-02
percent_home_owner                                              5.305e-02
census_2018_total_personal_income_median_curp_15years_and_over  8.034e-05
                                                               t value Pr(&gt;|t|)
(Intercept)                                                      7.098 1.45e-09
percent_no_qualification                                         7.002 2.13e-09
percent_home_owner                                              -5.752 2.92e-07
census_2018_total_personal_income_median_curp_15years_and_over  -4.101 0.000122
                                                                  
(Intercept)                                                    ***
percent_no_qualification                                       ***
percent_home_owner                                             ***
census_2018_total_personal_income_median_curp_15years_and_over ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.118 on 62 degrees of freedom
Multiple R-squared:  0.7607,    Adjusted R-squared:  0.7491 
F-statistic: 65.68 on 3 and 62 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We see that the <span class="math inline">\(r^2\)</span> has jumped to 76%…now Durbin Watson test and map again.</p>
<div class="cell" data-warniing="false">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>dw <span class="ot">&lt;-</span> <span class="fu">durbinWatsonTest</span>(model3)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(dw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  statistic p.value autocorrelation method             alternative
      &lt;dbl&gt;   &lt;dbl&gt;           &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;      
1      1.27       0           0.345 Durbin-Watson Test two.sided  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co">#and for future use, write the residuals out</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>model3_residuals <span class="ot">&lt;-</span> model3 <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">augment</span>(., census_authorities_data_norm_filter)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>ta_model3_data<span class="ot">&lt;-</span> ta<span class="sc">%&gt;%</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>(.)<span class="sc">%&gt;%</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(., model3_residuals,</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">by=</span><span class="fu">c</span>(<span class="st">"ta2018_v1"</span><span class="ot">=</span><span class="st">"area_code"</span>))</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(ta_model3_data) <span class="sc">+</span></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">".resid"</span>,</span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"RdYlBu"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This suggests that there could well be some spatial autocorrelation biasing our model, but can we test for spatial autocorrelation more systematically?</p>
<p>Yes - and some of you will remember this from the practical a few days ago. We can calculate a number of different statistics to check for spatial autocorrelation - the most common of these being Moran’s I.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate the centroids </span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>ta_model3_data <span class="ot">&lt;-</span> ta_model3_data <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ta2018_v1 <span class="sc">!=</span> <span class="st">"999"</span> <span class="sc">&amp;</span> ta2018_v1 <span class="sc">!=</span> <span class="st">"067"</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>coordsW <span class="ot">&lt;-</span> ta_model3_data<span class="sc">%&gt;%</span></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_centroid</span>()<span class="sc">%&gt;%</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_geometry</span>()</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(coordsW)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spdep)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Now we need to generate a spatial weights matrix </span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co">#We'll start with a simple binary matrix of queen's case neighbours</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>ta_nb <span class="ot">&lt;-</span> ta_model3_data <span class="sc">%&gt;%</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">poly2nb</span>(., <span class="at">queen=</span>T)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="co">#or nearest neighbours</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>ta_knn <span class="ot">&lt;-</span>coordsW <span class="sc">%&gt;%</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">knearneigh</span>(., <span class="at">k=</span><span class="dv">4</span>)</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>ta_knn_nb <span class="ot">&lt;-</span> ta_knn <span class="sc">%&gt;%</span></span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">knn2nb</span>()</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a><span class="co">#plot them</span></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ta_nb, <span class="fu">st_geometry</span>(coordsW), <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co">#create a spatial weights matrix object from these weights</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>ta_queens_weight <span class="ot">&lt;-</span> ta_nb <span class="sc">%&gt;%</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nb2listw</span>(., <span class="at">style=</span><span class="st">"W"</span>)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>ta_knn_4_weight <span class="ot">&lt;-</span> ta_knn_nb <span class="sc">%&gt;%</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nb2listw</span>(., <span class="at">style=</span><span class="st">"W"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>style</code> argument means the style of the output — <code>B</code> is binary encoding listing them as neighbours or not, <code>W</code> row standardised that we saw yesterday.</p>
<p>Now run a Moran’s I test on the residuals, first using queens neighbours</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>queen <span class="ot">&lt;-</span> ta_model3_data <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>()<span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(.resid)<span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>()<span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">moran.test</span>(., ta_queens_weight)<span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then nearest k-nearest neighbours</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>nearest_neighbour <span class="ot">&lt;-</span> ta_model3_data <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>()<span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(.resid)<span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>()<span class="sc">%&gt;%</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">moran.test</span>(., ta_knn_4_weight)<span class="sc">%&gt;%</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>queen</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  estimate1 estimate2 estimate3 statistic   p.value method           alternative
      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt;      
1     0.342   -0.0154   0.00818      3.95 0.0000387 Moran I test un… greater    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>nearest_neighbour</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 7
  estimate1 estimate2 estimate3 statistic    p.value method          alternative
      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;           &lt;chr&gt;      
1     0.334   -0.0154   0.00622      4.43 0.00000474 Moran I test u… greater    </code></pre>
</div>
</div>
<p>Observing the Moran’s I statistic for both Queen’s case neighbours and k-nearest neighbours of 4, we can see that the Moran’s I statistic is somewhere between 0.34 and 0.33. Remembering that Moran’s I ranges from between -1 and +1 (0 indicating no spatial autocorrelation) we can conclude that there is some weak to moderate spatial autocorrelation in our residuals.</p>
<p>This means that despite passing most of the assumptions of linear regression, we could have a situation here where the presence of some spatial autocorrelation could be leading to biased estimates of our parameters and significance values.</p>
</section>
</section>
</section>
</section>
<section id="spatial-regression-models" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="spatial-regression-models"><span class="header-section-number">4.4</span> Spatial regression models</h2>
<section id="the-spatial-lag-lagged-dependent-variable-model" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="the-spatial-lag-lagged-dependent-variable-model"><span class="header-section-number">4.4.1</span> The spatial lag (lagged dependent variable) model</h3>
<p>Running a Moran’s I test on the residuals from the model suggested that there might be some spatial autocorrelation occurring suggesting that places where the model over-predicted the percent of people smoking (those shown in blue in the map above with negative residuals) and under-predicted (those shown in red/orange) occasionally were near to each other.</p>
<p>Ward and Gleditsch (2008) describe this situation (where the value of our <span class="math inline">\(y\)</span> dependent variable - percent people who smoke - may be influenced by neighbouring values) and suggest the way to deal with it is to incorporate a <em>spatially-lagged</em> version of this variable amongst the independent variables on the right-hand side of the equation. In this case, Equation 1 would be updated to look like this:</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1x_i + \rho w_i.y_i + \epsilon_i\]</span></p>
<p>In this equation, <span class="math inline">\(w\)</span> is the spatial weights matrix you generated and <span class="math inline">\(w_i\)</span> is vector of all neighbouring areas (in our case, Territorial Authority) for any Territorial Authority <span class="math inline">\(y_i\)</span>. If using binary this will be a sum (e.g.&nbsp;the value of <span class="math inline">\(y\)</span> plotted against the sum of <span class="math inline">\(y\)</span> of the neighbouring Territorial Authority). This may be explained as a weighted sum as the non-neighbours will be removed, the weight being the neighbours If this is row standardised it will be a weighted average of the neighbouring <span class="math inline">\(y\)</span> values. Typically we use a <strong>row standardised</strong> matrix.</p>
<p>In this model, a positive value for the <span class="math inline">\(\rho w_i.y_i\)</span> parameter would indicate that the average value for the percent smoking is expected to be higher if, on average, neighbouring authorities also have a higher percentage of people who smoke.</p>
<ul>
<li><span class="math inline">\(\rho\)</span> denotes (represents) the spatial lag</li>
</ul>
<p>For more details on running a spatially lagged regression model and interpreting the outputs, see the chapter on spatially lagged models by <a href="https://methods.sagepub.com/book/spatial-regression-models/n2.xml">Ward and Gleditsch (2008) available online</a></p>
<section id="queens-case-lag" class="level4" data-number="4.4.1.1">
<h4 data-number="4.4.1.1" class="anchored" data-anchor-id="queens-case-lag"><span class="header-section-number">4.4.1.1</span> Queen’s case lag</h4>
<p>Now run a spatially-lagged regression model with a queen’s case weights matrix</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spatialreg)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>slag_dv_model2_queen <span class="ot">&lt;-</span> <span class="fu">lagsarlm</span>(percent_regular_smoker <span class="sc">~</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>               percent_no_qualification <span class="sc">+</span> </span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>               percent_home_owner <span class="sc">+</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>               census_2018_total_personal_income_median_curp_15years_and_over,</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> ta_model3_data, </span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>               <span class="fu">nb2listw</span>(ta_nb, <span class="at">style=</span><span class="st">"C"</span>), </span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">method =</span> <span class="st">"eigen"</span>)</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a><span class="co">#what do the outputs show?</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(slag_dv_model2_queen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  term                                     estimate std.error statistic  p.value
  &lt;chr&gt;                                       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 rho                                       2.33e-2 0.0311        0.748 4.55e- 1
2 (Intercept)                               2.76e+1 3.82          7.23  4.66e-13
3 percent_no_qualification                  5.08e-1 0.0720        7.06  1.67e-12
4 percent_home_owner                       -3.00e-1 0.0516       -5.82  5.99e- 9
5 census_2018_total_personal_income_media… -3.33e-4 0.0000777    -4.28  1.85e- 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#glance() gives model stats but this need something produced from a linear model</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co">#here we have used lagsarlm()</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(slag_dv_model2_queen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  r.squared   AIC   BIC deviance logLik  nobs
      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt;
1     0.763  294.  307.     276.  -141.    66</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>hold<span class="ot">&lt;-</span><span class="fu">summary</span>(slag_dv_model2_queen)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(hold<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -3.039236e-15</code></pre>
</div>
</div>
<p>Running the spatially-lagged model with a Queen’s case spatial weights matrix reveals that in this example, there is an insignificant and small effect associated with the spatially lagged dependent variable. However, a different conception of neighbours we might get a different outcome….</p>
<p>Here:</p>
<ul>
<li><p>Rho is our spatial lag (0.0232) that measures the variable in the surrounding spatial areas as defined by the spatial weight matrix. We use this as an extra explanatory variable to account for clustering (identified by Moran’s I). If significant it means that the percent of smokers in a unit vary based on the percent of smokers in the neighboring units. If it is positive it means as the percent of smokers increase in the surrounding units so does our central value</p></li>
<li><p>Log likelihood shows how well the data fits the model (like the AIC, which we cover later), the higher the value the better the models fits the data.</p></li>
<li><p>Likelihood ratio (LR) test shows if the addition of the lag is an improvement (from linear regression) and if that’s significant. This code would give the same output…</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lrtest</span>(slag_dv_model2_queen, model3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>Lagrange Multiplier (LM) is a test for the absence of spatial autocorrelation in the lag model residuals. If significant then you can reject the Null (no spatial autocorrelation) and accept the alternative (is spatial autocorrelcation)</p></li>
<li><p>Wald test (often not used in interpretation of lag models), it tests if the new parameters (the lag) should be included it in the model…if significant then the new variable improves the model fit and needs to be included. This is similar to the LR test and i’ve not seen a situation where one is significant and the other not. Probably why it’s not used!</p></li>
</ul>
<p>In this case we have spatial autocorrelation in the residuals of the model, but the model is not an improvement on OLS — this can also be confirmed with the AIC score (we cover that later) but the lower it is the better. Here it is 293, in OLS (model 3) it was 292. The Log likelihood for model 3 (OLS) was -141, here it is -140.</p>
<section id="lag-impacts" class="level5" data-number="4.4.1.1.1">
<h5 data-number="4.4.1.1.1" class="anchored" data-anchor-id="lag-impacts"><span class="header-section-number">4.4.1.1.1</span> Lag impacts</h5>
<p><strong>Warning</strong> according to Solymosi and Medina (2022) you must not not compare the coefficients of this to regular OLS…<strong>Why ?</strong></p>
<p>Well in OLS recall we can use the coefficients to say…a 1 unit change in the independent variable means a drop or rise in the dependent (for a 1% increase in percent with no qualifications the percent of smokers rises by 0.64 percent). <strong>BUT</strong> here the model is not consistent as the observations will change based on the weight matrix neighbours selected which might vary (almost certainly in a distance based matrix). This means we have a direct effect (standard OLS) and then an indirect effect in the model (impact of the spatial lag).</p>
<p>We can compute these direct and indirect effects using code from Solymosi and Medina (2022) and the <a href="https://r-spatial.github.io/spatialreg/reference/impacts.html">spatialreg</a> package. Here the <code>impacts()</code> function calculates the impact of the spatial lag. We can fit this to our entire spatial weights….</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spdep)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="co"># weight list is just the code from the lagsarlm</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>weight_list<span class="ot">&lt;-</span><span class="fu">nb2listw</span>(ta_knn_nb, <span class="at">style=</span><span class="st">"C"</span>)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>imp <span class="ot">&lt;-</span> <span class="fu">impacts</span>(slag_dv_model2_queen, <span class="at">listw=</span>weight_list)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>imp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Impact measures (lag, exact):
                                                                            Direct
percent_no_qualification dy/dx                                        0.5083288540
percent_home_owner dy/dx                                             -0.3001931060
census_2018_total_personal_income_median_curp_15years_and_over dy/dx -0.0003328803
                                                                          Indirect
percent_no_qualification dy/dx                                        1.206307e-02
percent_home_owner dy/dx                                             -7.123832e-03
census_2018_total_personal_income_median_curp_15years_and_over dy/dx -7.899525e-06
                                                                             Total
percent_no_qualification dy/dx                                        0.5203919197
percent_home_owner dy/dx                                             -0.3073169376
census_2018_total_personal_income_median_curp_15years_and_over dy/dx -0.0003407798</code></pre>
</div>
</div>
<p>Now it is appropriate to compare these coefficients to the OLS outputs…<strong>however</strong> if you have a very large matrix this might not work, instead a sparse matrix that uses approximation methods (see Solymosi and Medina (2022) and within that resource, Lesage and Pace 2009). This is beyond the scope of the content here, but essentially this makes the method faster on larger data…but only row standardised is permitted here…</p>
</section>
</section>
</section>
<section id="the-spatial-error-model" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="the-spatial-error-model"><span class="header-section-number">4.4.2</span> The spatial error model</h3>
<p>Another way of coneptualising spatial dependence in regression models is not through values of the dependent variable in some areas affecting those in neighbouring areas (as they do in the spatial lag model), but in treating the spatial autocorrelation in the residuals as something that we need to deal with, perhaps reflecting some spatial autocorrelation amongst unobserved independent variables or some other mis-specification of the model.</p>
<p>Ward and Gleditsch (2008) characterise this model as seeing spatial autocorrelation as a nuisance rather than being particularly informative, however it can still be handled within the model, albeit slightly differently.</p>
<p>The spatial error model can be written:</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1x_i + \lambda w_i\xi_i + \epsilon_i\]</span></p>
<p>where</p>
<ul>
<li><p><span class="math inline">\(\xi_i\)</span> is the spatial component of the error terms…in other words the residuals of the values in surrounding spatial units based on the weight matrix. The same rules apply as the lag (e.g.&nbsp;binary = sum, row standardisied = weighted average).</p></li>
<li><p><span class="math inline">\(\lambda\)</span> is a measure of correlation between neighbouring residuals.. “it indicates the extent to which the spatial component of the errors <span class="math inline">\(\xi_i\)</span> are correlated with one another for nearby observations” as per the weight matrix, Ward and Gleditsch (2008). <strong>If there is no correlation between the then this defaults to normal OLS regression</strong></p></li>
</ul>
<p>For more detail on the spatial error model, <a href="https://methods.sagepub.com/Book/spatial-regression-models/n3.xml">see Ward and Gleditsch (2008)</a></p>
<p>We can run a spatial error model on the same data below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>sem_1 <span class="ot">&lt;-</span> <span class="fu">errorsarlm</span>(percent_regular_smoker <span class="sc">~</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>               percent_no_qualification <span class="sc">+</span> </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>               percent_home_owner <span class="sc">+</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>               census_2018_total_personal_income_median_curp_15years_and_over,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> ta_model3_data, </span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>               <span class="fu">nb2listw</span>(ta_nb, <span class="at">style=</span><span class="st">"C"</span>), </span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">method =</span> <span class="st">"eigen"</span>)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(sem_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  term                                     estimate std.error statistic  p.value
  &lt;chr&gt;                                       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)                               2.53e+1 3.78           6.69 2.28e-11
2 percent_no_qualification                  5.71e-1 0.0686         8.33 0       
3 percent_home_owner                       -2.94e-1 0.0526        -5.58 2.41e- 8
4 census_2018_total_personal_income_media… -3.04e-4 0.0000796     -3.82 1.33e- 4
5 lambda                                    4.32e-1 0.118          3.65 2.62e- 4</code></pre>
</div>
</div>
<p>Comparing the results of the spatial error model with the spatially lagged model and the original OLS model, the suggestion here is that the spatially correlated errors in residuals lead to over/under estimations of the coefficients.</p>
<p>Note, here we can compare to OLS as there is no spatial lag.</p>
<p>The <span class="math inline">\(\lambda\)</span> parameter in the spatial error model is larger than the standard error and is significant, but the <span class="math inline">\(\rho\)</span> parameter is not larger than the standard error and is not significant.</p>
<p>So we can conclude that spatial dependence <em>might</em> be borne in mind when interpreting the results of this regression model. This suggests to us that the smoking is not influenced by neighbouring polygons (or smokers) but the errors between the neighours are related and we may have some mis-specification of the model - e.g.&nbsp;a missing variable.</p>
</section>
<section id="key-advice" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="key-advice"><span class="header-section-number">4.4.3</span> Key advice</h3>
<p>The <strong>lag</strong> model accounts for situations where the value of the dependent variable in one area might be associated with or influenced by the values of that variable in neighbouring zones (however we choose to define neighbouring in our spatial weights matrix). With our example, smoking in one neighbourhood might be related to smoking in another. You may be able to think of other examples where similar associations may occur. You might run a lag model if you identify spatial autocorrelation in the dependent variable (closer spatial units have similar values) with Moran’s I.</p>
<p>The <strong>error</strong> model deals with spatial autocorrelation (closer spatial units have similar values) of the residuals (vertical distance between your point and line of model – errors – over-predictions or under-predictions) again, potentially revealed though a Moran’s I analysis. The error model is not assuming that neighbouring independent variables are influencing the dependent variable but rather the assumption is of an <strong>issue with the specification of the model or the data used</strong> (e.g.&nbsp;clustered errors are due to some un-observed clustered variables not included in the model). For example, smoking prevelance may be similar in bordering neighbourhoods because residents in these neighbouring places come from similar socio-economic backgrounds and this was not included as an independent variable in the original model. There is no spatial process (no cross authority interaction) just a cluster of an un-accounted for but influential variable.</p>
</section>
</section>
<section id="gwr" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="gwr"><span class="header-section-number">4.5</span> GWR</h2>
<p>Rather than spatial autocorrelation causing problems with our model, it might be that a “global” regression model does not capture the full story. In some parts of our study area, the relationships between the dependent and independent variable may not exhibit the same slope coefficient.</p>
<p>If this occurs, then we have <strong><em>’non-stationarity</em></strong>’ - this is when the global model does not represent the relationships between variables that might vary locally.</p>
<section id="bandwidth" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="bandwidth"><span class="header-section-number">4.5.1</span> Bandwidth</h3>
<p>This part of the practical will only skirt the edges of GWR, for much more detail you should visit the <a href="http://gwr.nuim.ie/">GWR website</a> which is produced and maintained by Prof Chris Brunsdon and Dr Martin Charlton who originally developed the technique.</p>
<p>I should also acknowledge <a href="http://www.bris.ac.uk/cmpo/events/2009/segregation/gwr.pdf">the guide on GWR produced by the University of Bristol</a>, which was a great help when producing this exercise.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(spgwr)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>coordsW2 <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(coordsW)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>ta_model3_data_gwr <span class="ot">&lt;-</span> <span class="fu">cbind</span>(ta_model3_data,coordsW2)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>gwrbandwidth <span class="ot">&lt;-</span> <span class="fu">gwr.sel</span>(percent_regular_smoker <span class="sc">~</span></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>               percent_no_qualification <span class="sc">+</span> </span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>               percent_home_owner <span class="sc">+</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>               census_2018_total_personal_income_median_curp_15years_and_over,</span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> ta_model3_data_gwr,  </span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>                        <span class="at">coords=</span><span class="fu">cbind</span>(ta_model3_data_gwr<span class="sc">$</span>X, ta_model3_data_gwr<span class="sc">$</span>Y),</span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">adapt=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive q: 0.381966 CV score: 258.7724 
Adaptive q: 0.618034 CV score: 288.1859 
Adaptive q: 0.236068 CV score: 223.3048 
Adaptive q: 0.145898 CV score: 210.9782 
Adaptive q: 0.03932385 CV score: 212.4756 
Adaptive q: 0.1017793 CV score: 202.4218 
Adaptive q: 0.09472045 CV score: 203.8337 
Adaptive q: 0.111242 CV score: 202.5485 
Adaptive q: 0.1053937 CV score: 201.7625 
Adaptive q: 0.1063105 CV score: 201.6931 
Adaptive q: 0.1074627 CV score: 201.8976 
Adaptive q: 0.1061616 CV score: 201.6666 
Adaptive q: 0.1059668 CV score: 201.6645 
Adaptive q: 0.1057479 CV score: 201.7017 
Adaptive q: 0.1060531 CV score: 201.6499 
Adaptive q: 0.1060938 CV score: 201.6545 
Adaptive q: 0.1060124 CV score: 201.6567 
Adaptive q: 0.1060531 CV score: 201.6499 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>gwrbandwidth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1060531</code></pre>
</div>
</div>
<p>Setting <code>adapt=T</code> here means to automatically find the proportion of observations for the weighting using k nearest neighbours (an adaptive bandwidth), False would mean a global bandwidth and that would be in meters (as our data is projected).</p>
<p>Occasionally data can come with longitude and latitude as columns (e.g.&nbsp;WGS84) and we can use this straight in the function to save making centroids, calculating the coordinates and then joining - the argument for this is <code>longlat=TRUE</code> and then the columns selected in the <code>coords</code> argument e.g.&nbsp;<code>coords=cbind(long, lat)</code>. The distance result will then be in KM.</p>
<p>The optimal bandwidth is about 0.106 meaning 10.6% of all the total spatial units should be used for the local regression based on k-nearest neighbours. Which is about 7 of the 66 territorial authorities.</p>
<p>This approach uses cross validation to search for the optimal bandwidth, it compares different bandwidths to minimise model residuals — this is why we specify the regression model within <code>gwr.sel()</code>. It does this with a Gaussian weighting scheme (which is the default) - meaning that near points have greater influence in the regression and the influence decreases with distance - there are variations of this, but Gaussian is a fine to use in most applications. To change this we would set the argument <code>gweight = gwr.Gauss</code> in the <code>gwr.sel()</code> function — <code>gwr.bisquare()</code> is the other option. We don’t go into cross validation in this module.</p>
<p><strong>However</strong> we could set either the number of neighbours considered or the distance within which to considered points ourselves, manually, in the <code>gwr()</code> function below.</p>
<p>To set the number of other neighbours considered simply change the <code>adapt</code> argument to the value you want - it must be the number of neighbours divided by the total (e.g.&nbsp;to consider 20 neighbours it would be 20/66 and you’d use the value of 0.30)</p>
<p>To set the bandwidth, <strong>remove</strong> the <code>adapt</code> argument and replace it with <code>bandwidth</code> and set it, in this case, in meters.</p>
<p>To conclude, we can:</p>
<ul>
<li>set the bandwidth in <code>gwr.sel()</code> automatically using:
<ul>
<li>the number of neighbors</li>
<li>a distance threshold</li>
</ul></li>
<li>Or, we can set it manually in <code>gwr()</code> using:
<ul>
<li>a number of neighbors</li>
<li>a distance threshold</li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>BUT</strong> a problem with setting a fixed bandwidth is we assume that all variables have the same relationship across <strong>the same space (using the same number of neighbours or distance)</strong>. We can let these bandwidths vary as some relationships will operate on different spatial scales…this is called <strong>Multiscale GWR</strong> and Lex Comber recently said that all GWR should be Multisacle (oops!). We have already covered a lot here so i won’t go into it. If you are interested Lex has a <a href="https://rpubs.com/lexcomber/INIA_Session7">good tutorial on Multiscale GWR</a></p>
</div>
</div>
</section>
<section id="model" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="model"><span class="header-section-number">4.5.2</span> Model</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">#run the gwr model</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>gwr_model <span class="ot">=</span> <span class="fu">gwr</span>(percent_regular_smoker <span class="sc">~</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>               percent_no_qualification <span class="sc">+</span> </span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>               percent_home_owner <span class="sc">+</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>               census_2018_total_personal_income_median_curp_15years_and_over,</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> ta_model3_data_gwr,  </span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">coords=</span><span class="fu">cbind</span>(ta_model3_data_gwr<span class="sc">$</span>X, ta_model3_data_gwr<span class="sc">$</span>Y), </span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">adapt=</span>gwrbandwidth,</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>                <span class="co">#matrix output</span></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">hatmatrix=</span><span class="cn">TRUE</span>,</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>                <span class="co">#standard error</span></span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">se.fit=</span><span class="cn">TRUE</span>)</span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a><span class="co">#print the results of the model</span></span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a>gwr_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
gwr(formula = percent_regular_smoker ~ percent_no_qualification + 
    percent_home_owner + census_2018_total_personal_income_median_curp_15years_and_over, 
    data = ta_model3_data_gwr, coords = cbind(ta_model3_data_gwr$X, 
        ta_model3_data_gwr$Y), adapt = gwrbandwidth, hatmatrix = TRUE, 
    se.fit = TRUE)
Kernel function: gwr.Gauss 
Adaptive quantile: 0.1060531 (about 6 of 66 data points)
Summary of GWR coefficient estimates at data points:
                                                                      Min.
X.Intercept.                                                    3.3703e+00
percent_no_qualification                                        4.1815e-01
percent_home_owner                                             -4.4357e-01
census_2018_total_personal_income_median_curp_15years_and_over -9.2994e-04
                                                                   1st Qu.
X.Intercept.                                                    1.2399e+01
percent_no_qualification                                        4.8399e-01
percent_home_owner                                             -3.1838e-01
census_2018_total_personal_income_median_curp_15years_and_over -5.2518e-04
                                                                    Median
X.Intercept.                                                    1.7101e+01
percent_no_qualification                                        5.2129e-01
percent_home_owner                                             -2.4756e-01
census_2018_total_personal_income_median_curp_15years_and_over -9.6083e-05
                                                                   3rd Qu.
X.Intercept.                                                    3.4618e+01
percent_no_qualification                                        5.8085e-01
percent_home_owner                                             -1.8668e-01
census_2018_total_personal_income_median_curp_15years_and_over -2.1233e-05
                                                                      Max.
X.Intercept.                                                    4.8631e+01
percent_no_qualification                                        6.9995e-01
percent_home_owner                                             -1.6115e-01
census_2018_total_personal_income_median_curp_15years_and_over  1.9089e-04
                                                                Global
X.Intercept.                                                   27.9622
percent_no_qualification                                        0.5152
percent_home_owner                                             -0.3051
census_2018_total_personal_income_median_curp_15years_and_over -0.0003
Number of data points: 66 
Effective number of parameters (residual: 2traceS - traceS'S): 25.09782 
Effective degrees of freedom (residual: 2traceS - traceS'S): 40.90218 
Sigma (residual: 2traceS - traceS'S): 1.503921 
Effective number of parameters (model: traceS): 19.93781 
Effective degrees of freedom (model: traceS): 46.06219 
Sigma (model: traceS): 1.417184 
Sigma (ML): 1.183931 
AICc (GWR p. 61, eq 2.33; p. 96, eq. 4.21): 272.3116 
AIC (GWR p. 96, eq. 4.22): 229.5246 
Residual sum of squares: 92.51173 
Quasi-global R2: 0.9204215 </code></pre>
</div>
</div>
<p>The output from the GWR model reveals how the coefficients vary across the 66 territorial authorities New Zealand. You will see how the <strong>global</strong> coefficients are exactly the same as the coefficients in the earlier <code>lm</code> model. In this particular model, if we take percent with no qualification, we can see that the coefficients range from a minimum value of 0.41 (1 unit change in percent with no qualification resulting in a rise in percent smoking of 0.41) to 0.69 (1 unit change in percent with no qualification resulting in a rise in percent smoking of 0.69).</p>
<p>You will notice that the R-Squared value (Quasi global R-squared) has improved - this is not uncommon for GWR models, but it doesn’t necessarily mean they are definitely better than global models. The small number of cases (spatial areas) under the kernel means that GW models have been criticised for lacking statistical robustness.</p>
<p>The best way to compare models is with the <strong>AIC (Akaike Information Criterion) or for smaller sample sizes the sample-size adjusted AICc</strong>, especially when you number of points is <a href="https://towardsdatascience.com/introduction-to-aic-akaike-information-criterion-9c9ba1c96ced">less than 40!</a> Which it will be in GWR. The models must also be using the same data and be over the same study area!</p>
<p>AIC is calculated using the:</p>
<ul>
<li>number of independent variables</li>
<li>maximum likelihood estimate of the model (how well the model reproduces the data).</li>
</ul>
<p>The lower the value the better the better the model fit is, see <a href="https://www.scribbr.com/statistics/akaike-information-criterion/">scribbr</a> if you want to know more here..although this is enough to get you through most situations.</p>
<p>Coefficient ranges can also be seen for the other variables and they suggest some interesting spatial patterning.</p>
</section>
<section id="map-coefficients" class="level3" data-number="4.5.3">
<h3 data-number="4.5.3" class="anchored" data-anchor-id="map-coefficients"><span class="header-section-number">4.5.3</span> Map coefficients</h3>
<p>To explore this we can plot the GWR coefficients for different variables. Firstly we can attach the coefficients to our original dataframe - this can be achieved simply as the coefficients for each territoiral authority appear in the same order in our spatial points dataframe as they do in the original dataframe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(gwr_model<span class="sc">$</span>SDF)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "sum.w"                                                                
 [2] "X.Intercept."                                                         
 [3] "percent_no_qualification"                                             
 [4] "percent_home_owner"                                                   
 [5] "census_2018_total_personal_income_median_curp_15years_and_over"       
 [6] "X.Intercept._se"                                                      
 [7] "percent_no_qualification_se"                                          
 [8] "percent_home_owner_se"                                                
 [9] "census_2018_total_personal_income_median_curp_15years_and_over_se"    
[10] "gwr.e"                                                                
[11] "pred"                                                                 
[12] "pred.se"                                                              
[13] "localR2"                                                              
[14] "X.Intercept._se_EDF"                                                  
[15] "percent_no_qualification_se_EDF"                                      
[16] "percent_home_owner_se_EDF"                                            
[17] "census_2018_total_personal_income_median_curp_15years_and_over_se_EDF"
[18] "pred.se.1"                                                            
[19] "coord.x"                                                              
[20] "coord.y"                                                              </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co">#attach coefficients to original</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>ta_model3_data_gwr_results <span class="ot">&lt;-</span> ta_model3_data_gwr <span class="sc">%&gt;%</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">coefqualification =</span> results<span class="sc">$</span>percent_no_qualification,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">coefhomeowner =</span> results<span class="sc">$</span>percent_home_owner,</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">coefincome =</span> results<span class="sc">$</span>census_2018_total_personal_income_median_curp_15years_and_over_se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(ta_model3_data_gwr_results) <span class="sc">+</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"coefqualification"</span>, </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"RdBu"</span>, </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── tmap v3 code detected ───────────────────────────────────────────────────────</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[v3-&gt;v4] `tm_tm_polygons()`: migrate the argument(s) related to the scale of
the visual variable `fill` namely 'palette' (rename to 'values') to fill.scale
= tm_scale(&lt;HERE&gt;).
[v3-&gt;v4] `tm_polygons()`: use 'fill' for the fill color of polygons/symbols
(instead of 'col'), and 'col' for the outlines (instead of 'border.col').
[v3-&gt;v4] `tm_polygons()`: use `fill_alpha` instead of `alpha`.
[cols4all] color palettes: use palettes from the R package cols4all. Run
`cols4all::c4a_gui()` to explore them. The old palette name "RdBu" is named
"brewer.rd_bu"
Multiple palettes called "rd_bu" found: "brewer.rd_bu", "matplotlib.rd_bu". The first one, "brewer.rd_bu", is returned.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Taking the first coefficient we see that this varies across the country. A possible trend to explore further might be the inclusion or distance to tobacco retailers - both Wellington and Auckland have some of the highest coefficients, meaning a 1 unit (percent) change in no qualification returns a higher rise in percent of people smoking.</p>
</section>
<section id="significance" class="level3" data-number="4.5.4">
<h3 data-number="4.5.4" class="anchored" data-anchor-id="significance"><span class="header-section-number">4.5.4</span> Significance</h3>
<p>Of course, these results may not be statistically significant across the whole of New Zealand. Roughly speaking, if a coefficient estimate is more than 2 standard errors away from zero, then it is “statistically significant”.</p>
<p>Remember from earlier the standard error is “the average amount the coefficient varies from the average value of the dependent variable (its standard deviation). So, for 1% increase in percent with no qualifications, while the model says we might expect GSCE scores to drop by 0.6%, this might vary, on average, by about 0.08%. As a rule of thumb, we are looking for a lower value in the standard error relative to the size of the coefficient.”</p>
<p>To calculate standard errors, for each variable you can use a formula similar to this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#run the significance test</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="co"># abs gets the absolute vale - negative values are converted into positive value</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>sigTest <span class="ot">=</span> <span class="fu">abs</span>(gwr_model<span class="sc">$</span>SDF<span class="sc">$</span>percent_no_qualification)<span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span> gwr_model<span class="sc">$</span>SDF<span class="sc">$</span>percent_no_qualification_se</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="co">#store significance results</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>ta_model3_data_gwr_results <span class="ot">&lt;-</span> ta_model3_data_gwr_results <span class="sc">%&gt;%</span></span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gwrpercent_no_qualification_sig =</span> sigTest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(ta_model3_data_gwr_results) <span class="sc">+</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"gwrpercent_no_qualification_sig"</span>, </span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"RdYlBu"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── tmap v3 code detected ───────────────────────────────────────────────────────</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[v3-&gt;v4] `tm_tm_polygons()`: migrate the argument(s) related to the scale of
the visual variable `fill` namely 'palette' (rename to 'values') to fill.scale
= tm_scale(&lt;HERE&gt;).
[cols4all] color palettes: use palettes from the R package cols4all. Run
`cols4all::c4a_gui()` to explore them. The old palette name "RdYlBu" is named
"brewer.rd_yl_bu"
Multiple palettes called "rd_yl_bu" found: "brewer.rd_yl_bu", "matplotlib.rd_yl_bu". The first one, "brewer.rd_yl_bu", is returned.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04_spatial_models_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If this is greater than zero (i.e.&nbsp;the estimate is more than two standard errors away from zero), it is very unlikely that the true value is zero, i.e.&nbsp;it is statistically significant (at nearly the 95% confidence level)</p>
<p>This is a combination of two ideas:</p>
<ul>
<li>95% of data in a normal distribution is within two standard deviations of the mean</li>
<li>Statistical significance in a regression is normally measured at the 95% level. If the p-value is less than 5% — 0.05 — then there’s a 95% probability that a coefficient as large as you are observing didn’t occur by chance</li>
</ul>
<p>Combining these two means if…</p>
<ul>
<li>the coefficient is large in relation to its standard error <strong>and</strong></li>
<li>the p-value tells you if that largeness is statistically acceptable - at the 95% level (less than 5% — 0.05)</li>
</ul>
<p>You can be confident that in your sample, nearly all of the time, that is a real and reliable coefficient value.</p>
</section>
</section>
<section id="including-spatial-features" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="including-spatial-features"><span class="header-section-number">4.6</span> Including spatial features</h2>
<p>I mentioned at the start we could also try and include some spatial features within our model - for example the density of shops that sell tobacco? In a sense this is similar to what is termed a <strong>spatially omitted covariate</strong>… typically this means that the nearer something is the more influence it might have on our model (e.g.&nbsp;parks and house prices?).</p>
<p>However, we could only really calculate distance to tobacco shops from the centroid of the territorial authority as a new independent variable. But instead we could use density of shops per territorial authority!</p>
<p>Here, i will use open street map to calculate a density. I have downloaded the data from <a href="https://download.geofabrik.de/australia-oceania/new-zealand.html">Geofabrik</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>osm_pois <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"prac4_data/new-zealand-latest-free.shp/gis_osm_pois_a_free_1.shp"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gis_osm_pois_a_free_1' from data source 
  `C:\Users\Andy\OneDrive - University College London\Teaching\Guest\Oxford_26\spatial analysis of public health\spatial-analysis-of-public-health-data\prac4_data\new-zealand-latest-free.shp\gis_osm_pois_a_free_1.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 59185 features and 4 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -176.6404 ymin: -52.59086 xmax: 178.5443 ymax: -34.42668
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>osm_pois_filter <span class="ot">&lt;-</span> osm_pois <span class="sc">%&gt;%</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(fclass <span class="sc">==</span> <span class="st">"supermarket"</span> <span class="sc">|</span> fclass <span class="sc">==</span><span class="st">"convenience"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(., <span class="dv">2135</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s intersect with the territorial authority boundaries and calculate a density.</p>
<p><strong>Note</strong> that the <code>districts</code> object is in the correct CRS, however i beleive this is due to naming differences so we will transform it just incase.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>ta <span class="ot">&lt;-</span> ta <span class="sc">%&gt;%</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">st_transform</span>(., <span class="dv">2135</span>)</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>stores_joined <span class="ot">&lt;-</span> ta <span class="sc">%&gt;%</span></span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">lengths</span>(<span class="fu">st_intersects</span>(., osm_pois_filter)))<span class="sc">%&gt;%</span></span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()<span class="sc">%&gt;%</span></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>  <span class="co">#calculate area</span></span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">area=</span><span class="fu">st_area</span>(.))<span class="sc">%&gt;%</span></span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#then density of the points per ward</span></span>
<span id="cb83-10"><a href="#cb83-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">density=</span>n<span class="sc">/</span>area)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, we could use this in our model!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03_obesity.html" class="pagination-link" aria-label="Exploring the Spatial Distribution of Points in the Presence of Covariates - Fast-Food Outlets and Schools in London">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploring the Spatial Distribution of Points in the Presence of Covariates - Fast-Food Outlets and Schools in London</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05_food_bank_accessibility.html" class="pagination-link" aria-label="Food bank accessibility">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Food bank accessibility</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/oxford-mgh-2526/spatial-analysis-of-public-health-practicals/edit/main/04_spatial_models.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/oxford-mgh-2526/spatial-analysis-of-public-health-practicals/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>